import { useState } from 'react';
import { Monitor, RefreshCw, Terminal } from 'lucide-react';
import type { Installation, Provider, Receipt, Snapshot } from '../../../packages/protocol/schema';
import { api, date } from './api';
import { Badge, Empty, providerName } from './components';
import { Installations } from './Installations';

type Props = { snapshot: Snapshot; installations: Installation[]; providers: Provider[]; perform: (action: () => Promise<unknown>, message?: string) => Promise<void>; refresh: () => Promise<void>; onMessage: (message: string) => void; onSettings: () => void; onEnroll: () => void; onCompare: (itemId: string, targetId: string) => void; onUninstall: (receiptId: string) => void };
/** The Machines section: this machine's enrolled environments, live drift checks and installed copies. */
export function MachinesView({ snapshot, installations, providers, perform, refresh, onMessage, onSettings, onEnroll: _onEnroll, onCompare, onUninstall }: Props) {
  const [drift, setDrift] = useState<(Receipt & { drifted: boolean; checkedAt: string; error?: string })[]>([]);
  return <><div className="machine-banner"><div className="machine-icon"><Monitor size={30} /></div><div><h3>This machine</h3><p>Local execution · {snapshot.targets.length} enrolled environments</p><small>Personal skill folders are set up in Settings. Project folders are enrolled here.</small></div><button className="button" onClick={() => void perform(async () => { setDrift(await api('deploy.drift')); await refresh(); }, 'Installed files checked')}><RefreshCw size={15} />Check drift</button></div><div className="cards-grid">{snapshot.targets.map(t => <div className="environment-card" key={t.id}><div className="section-heading"><div className={`provider-mark ${t.provider}`}><Terminal size={20} /></div><Badge status={t.scope} /></div><h3>{t.name}</h3><p>{providerName[t.provider]} · {t.scope === 'project' ? 'project folder' : 'personal folder'}{t.profile && t.profile.toLowerCase() !== t.scope ? ` · ${t.profile}` : ''}</p><code className="path-text">{t.root}</code><div className="environment-footer"><span>{snapshot.receipts.filter(r => r.targetId === t.id && r.status === 'applied').length} install receipts</span><span>{providers.find(p => p.id === t.provider)?.available ? 'Client detected' : 'Client not on PATH'}</span></div><div className="wrap-actions"><button className="button danger-text" onClick={() => void perform(async () => { await api('targets.remove', { id: t.id, confirm: true }); await refresh(); }, 'Environment removed; installed files were left in place')}>Stop managing</button></div></div>)}</div>{!snapshot.targets.length && <Empty icon={<Monitor size={28} />} title="Choose where approved skills belong." action={<button className="button" onClick={() => onSettings()}>Set up skill locations</button>}>Personal skill folders for Codex, Claude Code and Copilot are one click away in Settings. Project folders can be enrolled here.</Empty>}{drift.length > 0 && <section className="settings-card"><h3>Live destination checks</h3>{drift.map(d => <div className="drift-row" key={d.id}><code className="path-text">{d.destination}</code><Badge status={d.drifted ? 'drifted' : 'current'} />{d.drifted && snapshot.items.find(i => i.id === d.itemId)?.kind === 'skill' && <button className="button" title="See which files differ and how" onClick={() => onCompare(d.itemId, d.targetId)}>Compare</button>}<small>{date(d.checkedAt)}</small></div>)}</section>}<Installations snapshot={snapshot} installations={installations} onUninstall={onUninstall} onCompare={i => onCompare(i.itemId, i.targetId)} /><div className="notice"><b>Remote environments</b><p>SSH execution and reconnect recovery are not implemented yet. This release never falls back from a remote request to this machine.</p></div><button className="button" onClick={() => void perform(async () => { const result = await api('deploy.recover'); onMessage(JSON.stringify(result)); await refresh(); })}>Recover interrupted local installs</button></>;
}
