// Regenerates packages/agent/guidance.ts from the Markdown sources so the guidance ships inside the bundled app and the CLI.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const folder = fileURLToPath(new URL('../packages/agent/guidance/', import.meta.url));
const read = file => fs.readFileSync(path.join(folder, file), 'utf8');
const body = read('writing-for-agents.md').replace(/^---[\s\S]*?---\r?\n/, '').replace('[`SKILL-MECHANICS.md`](SKILL-MECHANICS.md)', 'the "Skill mechanics" section below').trim();
const mechanics = read('skill-mechanics.md').replace('[`writing-for-agents`](SKILL.md)', 'writing-for-agents').trim();
/** Every file under `dir`, by `/`-separated relative path, sorted so the output is stable. */
const tree = dir => {
  const files = {};
  const visit = relative => { for (const entry of fs.readdirSync(path.join(dir, relative), { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) { const name = relative ? `${relative}/${entry.name}` : entry.name; if (entry.isDirectory()) { if (entry.name !== '__pycache__') visit(name); } else if (entry.isFile()) files[name] = fs.readFileSync(path.join(dir, name), 'utf8'); } };
  visit(''); return files;
};
const skill = { 'SKILL.md': read('writing-for-agents.md'), 'SKILL-MECHANICS.md': read('skill-mechanics.md') };
const out = `// Generated by scripts/guidance.mjs from packages/agent/guidance/. Edit the sources there, then run: node scripts/guidance.mjs
/** Kiln's house guidance for shaping skills; sent to the agent that drafts or scores a skill. */
export const writingForAgents = ${JSON.stringify(`${body}\n\n${mechanics}`)};
/** The same guidance as a skill folder (SKILL.md and SKILL-MECHANICS.md), installed beside Tune runs. */
export const writingForAgentsSkill: Record<string, string> = ${JSON.stringify(skill, null, 2)};
/** The user's tune-skill (packages/agent/guidance/tune-skill), installed into each Tune run's folder. */
export const tuneSkill: Record<string, string> = ${JSON.stringify(tree(path.join(folder, 'tune-skill')), null, 2)};
`;
fs.writeFileSync(new URL('../packages/agent/guidance.ts', import.meta.url), out);
console.log('guidance.ts written');
