// Regenerates packages/agent/guidance.ts from the Markdown sources so the guidance ships inside the bundled app and the CLI.
import fs from 'node:fs';
const read = file => fs.readFileSync(new URL(`../packages/agent/guidance/${file}`, import.meta.url), 'utf8');
const body = read('writing-for-agents.md').replace(/^---[\s\S]*?---\r?\n/, '').replace('[`SKILL-MECHANICS.md`](SKILL-MECHANICS.md)', 'the "Skill mechanics" section below').trim();
const mechanics = read('skill-mechanics.md').replace('[`writing-for-agents`](SKILL.md)', 'writing-for-agents').trim();
const out = `// Generated by scripts/guidance.mjs from packages/agent/guidance/*.md. Edit the Markdown, then run: node scripts/guidance.mjs\n/** Kiln's house guidance for shaping skills; sent to the agent that drafts a skill. */\nexport const writingForAgents = ${JSON.stringify(`${body}\n\n${mechanics}`)};\n`;
fs.writeFileSync(new URL('../packages/agent/guidance.ts', import.meta.url), out);
console.log('guidance.ts written');
